# -*- coding: utf-8 -*-
"""calculadorainteligente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147auv9bkKYDZjAx_nobba8ZmjYe-19id
"""

# Apresentação do script
print("Olá! Essa é uma calculadora inteligente")
#variável para laço de repetição
while True:
  resp = input("Deseja realizar uma operação? (s/n) ")
  if resp == 'n':
    print("Finalizando Script.")
    break
#coleta de dados para a operação
  operador = input("Digite a operação matemática desejada: ")
  x = float(input("Digite o primeiro número da operação: "))
  y = float(input("Digite o segundo número da operação: "))
#laço de repetição
  if operador == '*':
    print(x,"*",y,"=",x*y)
  if operador == '+':
      print(x,"+",y,"=",x+y)
  if operador == '/':
    print(x,"/",y,"=",x/y)
  if operador == '-':
    print(x,"-",y,"=",x-y)
  else:
    print("Verifique a operação digitada.")